import os
import json
import glob

def generate_reports():
    print("Generating Automated Evaluation Reports...")
    metrics_dir = '/workspace/results/metrics'
    report_path = '/workspace/reports/evaluation/comparison_report.md'
    
    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    
    # Find all evaluated models (those with .json but not _compute.json)
    json_files = glob.glob(os.path.join(metrics_dir, '*.json'))
    models = [os.path.basename(f).replace('.json', '') for f in json_files if not f.endswith('_compute.json')]
    
    table_header = "| Metric |"
    table_divider = "|--------|"
    for m in models:
        table_header += f" {m} |"
        table_divider += "---|"
        
    metrics_to_show = {
        'bbox_mAP': 'mAP',
        'bbox_mAP_s': 'mAPS',
        'FLOPs': 'FLOPs',
        'Params': 'Params'
    }
    
    rows = {m_key: f"| {m_label} |" for m_key, m_label in metrics_to_show.items()}
    
    for m in models:
        # Load COCO metrics
        coco_path = os.path.join(metrics_dir, f"{m}.json")
        with open(coco_path, 'r') as f:
            coco = json.load(f)
            
        # Load Compute metrics
        compute_path = os.path.join(metrics_dir, f"{m}_compute.json")
        if os.path.exists(compute_path):
            with open(compute_path, 'r') as f:
                compute = json.load(f)
        else:
            compute = {}
            
        combined = {**coco, **compute}
        
        for k in metrics_to_show.keys():
            val = combined.get(k, 'N/A')
            if isinstance(val, float):
                val = f"{val:.3f}"
            rows[k] += f" {val} |"
            
    with open(report_path, 'w') as f:
        f.write("# Stage 4 — Automated Comparison Report\n\n")
        f.write("This report is automatically generated by the Stage 4 Evaluation Framework.\n\n")
        f.write(table_header + "\n")
        f.write(table_divider + "\n")
        for r in rows.values():
            f.write(r + "\n")
            
    print(f"Report successfully generated at {report_path}")

if __name__ == '__main__':
    generate_reports()
